services:
  # The Shared Database (Used by Spring Boot & Python)
  postgres:
    image: pgvector/pgvector:pg16
    container_name: sentinel-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Defines where the data is stored permanently
volumes:
  postgres_data: